music_mage_app/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [ 
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

music_mage_app/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # works
    path('', views.index, name='index'),
    # works
    path('mage.html/', views.TrackFormView.as_view(), name='mage'),
    # does not work 
    path('mage.html/find/<path:track_id>/', views.results, name='results'),
    # works
    path('mage.html/find/', views.find, name='find'),
]

# path('mage.html/', views.mage, name='mage'),
# path('mage.html/<int:track_id>/vote/', views.vote, name='vote'),
# path('mage.html/<int:pk>/', views.DetailView.as_view(), name='detail'),
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     path('<int:question_id>/results/', views.results, name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

music_mage_app/mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
import csv
import pandas as pd

# Create your models here.

# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')

#     def __str__(self):
#         return self.question_text
    
#     def was_published_recently(self):
#         return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
    
#     def __str__(self):
#         return self.choice_text

class SongTracks(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    genre = models.CharField(max_length=100)
    track_name = models.CharField(max_length=100)
    artist_name = models.CharField(max_length=100)
    popularity = models.IntegerField()
    valence = models.FloatField()
    energy  = models.FloatField()
    danceability  = models.FloatField()
    acousticness  = models.FloatField()
    tempo  = models.FloatField()
    speechiness  = models.FloatField()
    mode  = models.IntegerField()
    instrumentalness = models.FloatField()

    # def __str__(self):
    #     return self.objects.all()

    # def__str__(self):
    #     return self.objects.all()

# class df(models.Model):
#     with open('music_characteristics_dataset.csv') as file:
#         reader = csv.reader(file)
#         for row in reader:
#             _, created = song_track.objects.get_or_create(
#                 id=row[0],
#                 genre=row[1],
#                 track_name=row[2],
#                 artist_name=row[3],
#                 popularity=row[4],
#                 valence=row[5],
#                 energy=row[6],
#                 danceability=row[7],
#                 acousticness=row[8],
#                 tempo=row[9],
#                 speechiness=row[10],
#                 mode=row[11],
#                 instrumentalness=row[12],
#                 )

    



   

music_mage_app/mysite/polls/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from .models import SongTracks

class TrackForm(forms.Form):
    sample_track = forms.CharField(label='Song Track', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Track Name', 'style': 'width: 400px;', 'class': 'form-control', 'align':'center'}))
    sample_artist = forms.CharField(label='Artist Name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Artist Name', 'style': 'width: 400px;', 'class': 'form-control', 'align':'center'}))

    # def send_email(self):
    #     # send email using the self.cleaned_data dictionary
    #     pass

# class TrackForm(forms.ModelForm):

#     class Meta:
#         model = SongTracks
#         fields = ('sample_track','sample_artist')

music_mage_app/mysite/polls/views.py
# Import django modules
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
# , get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.generic.base import RedirectView 
from django.views.generic.edit import FormView
from django.core.exceptions import *
from django.core.cache import cache
from django.conf import settings
from django.utils.encoding import smart_bytes

# Import models
from .forms import TrackForm
from .models import SongTracks

# Import modules
import pandas as pd
import numpy as np
import os
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from decouple import config
import csv

# HOMEPAGE
def index(request):
    return render(request, 'polls/index.html')

# MUSIC MAGE SEARCH ENGINE PAGE
class TrackFormView(FormView):
    template_name = 'polls/mage.html'
    form_class = TrackForm
    # success_url = 'mage.html/find/'
    def form_valid(self, form):
    #     # This method is called when valid form data has been POSTed.
    #     # It should return an HttpResponse
        print(form.cleaned_data)

# OPTIONAL SONG DETAIL PAGE WITH ALBUM COVER ART, ETC.
# def detail(request, track_id):
#     track_id = cache.get('track_id')
#     return render(request, 'polls/detail.html', {'track_id':track_id})

# LOAD DATA INTO SONGTRACKS MODEL
def get_table():
    p = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'music_characteristics_dataset.csv')
    with open(p, encoding='utf-8') as f:
        reader = csv.reader(f)
        # Skip the header row of the CSV file
        next(reader)
        
        for row in reader:
            obj, created = SongTracks.objects.get_or_create(
            id=row[0],
            genre=row[1],
            track_name=row[2],
            artist_name=row[3],
            popularity=row[4],
            valence=row[5],
            energy=row[6],
            danceability=row[7],
            acousticness=row[8],
            tempo=row[9],
            speechiness=row[10],
            mode=row[11],
            instrumentalness=row[12],
            )
            try:
                created.save()
            except:
                # if there is a problem anywhere, you wanna know about it
                print("There was a problem")

# ACTIVATE DATA LOADING OR ACCESS DATA AND RETURN A DATAFRAME
def df():
    if SongTracks.objects.count() == 0:
        get_table()
    else:
        data = SongTracks.objects.all().values()
        df = pd.DataFrame(data)
        df["mood_vec"] = df[["valence", "energy", "acousticness", "instrumentalness", "speechiness", "mode"]].values.tolist()
        cache.set('df', df, 60)
        return df

# CREATE CLIENT FUNCTION TO CONNECT US TO SPOTIFY
def client():
    client_id = settings.SPOTIPY_CLIENT_ID
    client_secret = settings.SPOTIPY_CLIENT_SECRET
    client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
    spotify = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
    cache.get_or_set('spotify', spotify)
    return spotify

# CREATE FUNCTION TO MATCH INPUT TEXT WITH SPOTIFY SONG TRACK ID
def get_track_id(request):
    """Return the top 5 songs that match in mood."""

    # 1. Create empty list to hold track_id
    track_id = []
    
    # 2. Save the input text in variables
    form = TrackForm(request.POST)
    if form.is_valid():
        sample_track = form.cleaned_data['sample_track']
        sample_artist = form.cleaned_data['sample_artist']
        print(f'{sample_track} by {sample_artist}')
        cache.set('sample_track', sample_track, 10)
        cache.set('sample_artist', sample_artist, 10)

    try:
    # 3. Search Spotify for correct track
        track_result = client().search(q=f'track:{sample_track} artist:{sample_artist}', limit=1, type='track')
    except:
        return ("no such song track")
        
    # 4. Save track id
    for i, tdata in enumerate(track_result['tracks']['items']):
        track_id.append(tdata['id'])

    track_id = track_id[0]
    # cache.set('track_id', track_id, 10)
    return track_id


# CREATE RECOMMENDATION FUNCTION
def recommend(track_id, ref_df, n_recs = 5):
    
    # Get audio features of given track from spotify api
    track_features = client().audio_features(track_id)[0]
    # Combine into mood vector
    track_moodvec = np.array([track_features['valence'], track_features['energy'], track_features['acousticness'], 
                              track_features['instrumentalness'], track_features['speechiness'], 
                              track_features['mode']])
    
    # Compute distances to all reference tracks
    ref_df["distances"] = ref_df["mood_vec"].apply(lambda x: np.linalg.norm(track_moodvec-np.array(x)))
    # Sort by popularity
    ref_df_sorted = ref_df.sort_values(by = "popularity", ascending = True)
    # Sort distances from lowest to highest
    ref_df_sorted = ref_df.sort_values(by = "distances", ascending = True) 
    
    # If the input track is in the reference set, it will have a distance of 0, but should not be recommended
    ref_df_sorted = ref_df_sorted[ref_df_sorted["id"] != track_id]
    ref_df_sorted = ref_df_sorted.set_index('track_name')
    # cache.set('ref_df_sorted', ref_df_sorted[['artist_name', 'genre']].iloc[:n_recs], 10)

    return ref_df_sorted[['artist_name', 'genre']].iloc[:n_recs]

# CREATE FUNCTION THAT SEARCHES FOR SONG RECOMMENDATIONS
def find(request):
    form = TrackForm(request.POST)
    if form.is_valid():
        sample_track = form.cleaned_data['sample_track']
        sample_artist = form.cleaned_data['sample_artist']
    # if the user clicks search
    if request.method == 'POST':
        # if track_id is not None:   
        try:
            # get the track_id and dataframe
            track_id = get_track_id(request)
            ref_df = df()
            # Try to retrieve song recommendations
            recs = recommend(track_id=track_id, ref_df=ref_df)
            # return render(request,'mage.html', context=results)
        except:
            # if it doesn't work then reload the music mage search engine page
            return render(request, 'polls/mage.html', {
            'error_message': "Something went wrong. Please try again.",
            })
               
        # Display the page with the results  
        else:
            # context = {'recs': recs, 'sample_track':sample_track.upper(), 'sample_artist':sample_artist.upper()}
            return HttpResponseRedirect(reverse('polls:results', args=(track_id,)))
            # 'track_id':track_id.encode('UTF-8')
            # response = results(request, track_id.encode('UTF-8'), context)
            # return response
             # if track_id is not None:
    #       return HttpResponseRedirect(track_id.encode('UTF-8'))
            # title = sample_track.lower()
            # recs = recs.copy().to_html(classes='table table-striped text-center', justify='center')
            # classes='table table-striped text-center', justify='center'
            # cache.set('recs', recs, 120)

    # if no one clicks the search button render the mage page       
    else:
        # return render(request,'polls/mage.html')
        return render(request,'polls/mage.html')

# FUNCTION TO LOAD RECOMMENDATION RESULTS
def results(request, track_id):
    sample_track = cache.get('sample_track') 
    sample_artist = cache.get('sample_artist')
    ref_df = df()
    recs = recommend(track_id=track_id, ref_df=ref_df).copy()
    recs = recs.to_html(classes='table table-striped text-center', justify='center')
    context = {'recs': recs, 'sample_track':sample_track.upper(), 'sample_artist':sample_artist.upper(), 'track_id': id}
    # print('hello')
    # recs = cache.get('recs')
    # track_id = cache.get('track_id')
    return render(request, 'polls/results.html', context=context)

#Now, if you want to redirect to results from find along with its context, you can modify your functions like this.
# def results(request, newContext={}): 
#  ..
#  ..
#  context = {
#  ..
#  }
#  context.update(newContext)
#  ..
#  return render(request, "../../xyz.html", context=context)

# def find(request) : 
#  ..
#  context = {
#  ..
#  }
#  ..
#  response = results(request, context)
#  return response

music_mage_app/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Music Mage</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}">
</head>
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'polls:index' %}">Music Mage</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="#!">Sign Up</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Content section 1-->
    <section id="scroll">
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'polls/record.jpg' %}" alt="http://images.clipartpanda.com/record-clipart-cliparti1_record-clipart_01.jpg" /></div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <br></br>
                        <h3 class="display-4">From those retro record hits...</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p> -->
                        <form action="{% url 'polls:find' track_id %}" method="POST">
                            {% csrf_token %}
                            <fieldset>
                                <legend><h1>{{ TrackForm.sample_track }}</h1></legend>
                                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                                <!-- {% for choice in question.choice_set.all %}
                                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                                {% endfor %} -->
                            </fieldset>
                            <input type="submit" value="Submit">
                        </form>

                        <!-- <form method="POST" action="{% url 'polls:detail' %}">
                            {% csrf_token %}
                            <input type="text" name="textfield">
                            
                            <button type="submit">Submit</button>
                        </form> -->

                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul> -->

    <!-- Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Music Mage 2021</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

music_mage_app/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Welcome to Music Mage!</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'polls:index' %}">Music Mage</a>
                <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#!">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                    </ul>
                </div> -->
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">Has Your Old Music Lost its Magic?</h1>
                    <h2 class="masthead-subheading mb-0">Give Music Mage a Try!</h2>
                    <a class="btn btn-primary btn-xl rounded-pill mt-5" href="{% url 'polls:mage' %}">Click here!</a>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        <!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'polls/record.jpg' %}" alt="http://images.clipartpanda.com/record-clipart-cliparti1_record-clipart_01.jpg" /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">From those retro record hits...</h2>
                            <p>Music Mage is a music recommendation system that finds music for you based on a single sample track that you provide. Using Spotify's API, we retrieve data on your song, put it into a vector, and compare it with thousands of other songs in our database. The closer the vector values are, the more similar the songs are in style, sound, and mood.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 2-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'polls/cd.jpg' %}" alt="https://thumbs.dreamstime.com/b/cd-media-23024869.jpg" /></div>
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <h2 class="display-4">To the top pop singles...</h2>
                            <p>After sorting all these songs according to how closely they match your sample track, we then sort them by popularity to make sure we are giving you the best possible results. Of these, we return to you the top five matches, hoping that at least one or two of them you have never seen before.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 3-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'polls/app.png' %}" alt="https://ioshacker.com/wp-content/uploads/2019/07/Music-app-feat.jpg" /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">Let the music magic begin!</h2>
                            <p>Start by typing in the name of one your favorite song tracks into the Music Mage search box. Next, enter in the name of the artist, band, or ensemble that performed it. Sometimes popular classics have been recorded many times by multiple different artists, so don't skip this important piece! Finally, hit the 'Get Recommendations' button and check out the new song suggestions that Music Mage has for you!</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Music Mage 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

music_mage_app/mysite/polls/templates/polls/mage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Music Mage</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        {% load cache %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}">
        <style>
            a {
              color: #ffffff;
            }
          </style>
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'polls:index' %}">Music Mage</a>
            <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="#!">Sign Up</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                </ul>
            </div> -->
        </div>
    </nav>
    <header class="masthead text-center text-white">
        <div class="masthead-content">
            <div class="container px-5">
                <h1 class="masthead-heading mb-0">Music Mage</h1>
                <!-- <h2 class="masthead-subheading mb-0">
                    {% if latest_question_list %}
                    <ul>
                        {% for question in latest_question_list %}
                            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                        {% endfor %}
                    </ul>
                        {% else %}
                            <p>No polls are available.</p>
                    {% endif %}</h2> -->
                    
                    <form action="{% url 'polls:find' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group" ALIGN='center'>
                          <!-- <label for="sample_track">Song Track</label> -->
                          {{ form.sample_track }}
                          <!-- <input name="sample_track" type="text" class="form-control" id="sample_track" placeholder="Title"> -->
                        </div>
                        <br>
                        <div class="form-group" ALIGN='center'>
                          <!-- <label for="sample_artist">Artist Name</label> -->
                          {{ form.sample_artist }}
                          <!-- <input name="sample_artist" type="text" class="form-control" id="sample_artist" placeholder="John Smith"> -->
                        </div>
                        <br>
                        <!-- {{ form.sample_track }} -->
                        <div class="form-group">
                        <button type="submit" value='search' class="btn btn-primary">Get Recommendations</button>
                        </div>
                      </form>
            </div>
        </div>
        <div class="bg-circle-1 bg-circle"></div>
        <div class="bg-circle-2 bg-circle"></div>
        <div class="bg-circle-3 bg-circle"></div>
        <div class="bg-circle-4 bg-circle"></div>
    </header>
    <!-- Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Music Mage 2021</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>